// src/lib/supabaseClient.ts
import { createClient } from "@supabase/supabase-js";

// Application type matching Supabase schema
// Application type matching Supabase schema
export interface Application {
  // id will be generated by Supabase (UUID)
  id?: string;
  application_id: string;
  full_name: string;
  email: string;
  phone: string;
  whatsapp: string;
  city: string;
  education_level: string;
  selected_field: string;
  skills: string;
  portfolio_url: string;
  why_internship: string;
  availability: string;
  consent: boolean;
  status: string;
  created_at?: string;
}

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn("Supabase credentials are not set. Supabase operations will be skipped.");
}

const supabase = supabaseUrl && supabaseAnonKey ? createClient(supabaseUrl, supabaseAnonKey) : null;

/** Insert a new application */
export async function insertApplication(app: Application): Promise<boolean> {
  if (!supabase) return false;
  const { data, error } = await supabase.from("internship_applications").insert([app]);
  if (error) {
    console.error("Supabase insert error:", error);
    return false;
  }
  return true;
}

/** Fetch all applications, sorted by createdAt descending */
export async function fetchApplications(): Promise<Application[]> {
  if (!supabase) return [];
  const { data, error } = await supabase
    .from("internship_applications")
    .select("*")
    .order("created_at", { ascending: false });
  if (error) {
    console.error("Supabase fetch error:", error);
    return [];
  }
  return data as Application[];
}

/** Update the status of an application */
export async function updateStatus(id: string, status: Application["status"]): Promise<boolean> {
  if (!supabase) return false;
  const { error } = await supabase
    .from("internship_applications")
    .update({ status })
    .eq("id", id);
  if (error) {
    console.error("Supabase update error:", error);
    return false;
  }
  return true;
}
